version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: docker_db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  app:
    build:
      context: .
      dockerfile: Docker-App/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/docker_db
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    depends_on:
      - db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbitreciever:
    build:
      context: .
      dockerfile: Docker-RabbitMQ/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
  rabbitpublisher:
    build:
      context: .
      dockerfile: Docker-RabbitMQ-Server2/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
